//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace JZWebService.SapOa12Webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_OA_OA12_OUTBinding", Namespace="http://jiuzhou.com/OA")]
    public partial class SI_OA_OA12_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_OA_OA12_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_OA_OA12_OUTService() {
            this.Url = global::JZWebService.Properties.Settings.Default.JZWebService_SapOa12Webservice_SI_OA_OA12_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_OA_OA12_OUTCompletedEventHandler SI_OA_OA12_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute("MT_OA_OA12_Resp", Namespace="http://jiuzhou.com/OA")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DT_OA_OA12_RespITEM[] SI_OA_OA12_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jiuzhou.com/OA")] DT_OA_OA12 MT_OA_OA12) {
            object[] results = this.Invoke("SI_OA_OA12_OUT", new object[] {
                        MT_OA_OA12});
            return ((DT_OA_OA12_RespITEM[])(results[0]));
        }
        
        /// <remarks/>
        public void SI_OA_OA12_OUTAsync(DT_OA_OA12 MT_OA_OA12) {
            this.SI_OA_OA12_OUTAsync(MT_OA_OA12, null);
        }
        
        /// <remarks/>
        public void SI_OA_OA12_OUTAsync(DT_OA_OA12 MT_OA_OA12, object userState) {
            if ((this.SI_OA_OA12_OUTOperationCompleted == null)) {
                this.SI_OA_OA12_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_OA_OA12_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_OA_OA12_OUT", new object[] {
                        MT_OA_OA12}, this.SI_OA_OA12_OUTOperationCompleted, userState);
        }
        
        private void OnSI_OA_OA12_OUTOperationCompleted(object arg) {
            if ((this.SI_OA_OA12_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_OA_OA12_OUTCompleted(this, new SI_OA_OA12_OUTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA12 {
        
        private DT_OA_OA12HEAD hEADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_OA_OA12HEAD HEAD {
            get {
                return this.hEADField;
            }
            set {
                this.hEADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA12HEAD {
        
        private string i_PERNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_PERNR {
            get {
                return this.i_PERNRField;
            }
            set {
                this.i_PERNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA12_RespITEM {
        
        private string aWARTField;
        
        private string aTEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AWART {
            get {
                return this.aWARTField;
            }
            set {
                this.aWARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATEXT {
            get {
                return this.aTEXTField;
            }
            set {
                this.aTEXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SI_OA_OA12_OUTCompletedEventHandler(object sender, SI_OA_OA12_OUTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SI_OA_OA12_OUTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SI_OA_OA12_OUTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_OA_OA12_RespITEM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_OA_OA12_RespITEM[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591