//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace JZWebService.SapOa04Webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SI_OA_OA04_OUTBinding", Namespace="http://jiuzhou.com/OA")]
    public partial class SI_OA_OA04_OUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SI_OA_OA04_OUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SI_OA_OA04_OUTService() {
            this.Url = global::JZWebService.Properties.Settings.Default.JZWebService_SapOa04Webservice_SI_OA_OA04_OUTService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SI_OA_OA04_OUTCompletedEventHandler SI_OA_OA04_OUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SI_OA_OA04_OUT([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jiuzhou.com/OA")] DT_OA_OA04 MT_OA_OA04) {
            this.Invoke("SI_OA_OA04_OUT", new object[] {
                        MT_OA_OA04});
        }
        
        /// <remarks/>
        public void SI_OA_OA04_OUTAsync(DT_OA_OA04 MT_OA_OA04) {
            this.SI_OA_OA04_OUTAsync(MT_OA_OA04, null);
        }
        
        /// <remarks/>
        public void SI_OA_OA04_OUTAsync(DT_OA_OA04 MT_OA_OA04, object userState) {
            if ((this.SI_OA_OA04_OUTOperationCompleted == null)) {
                this.SI_OA_OA04_OUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSI_OA_OA04_OUTOperationCompleted);
            }
            this.InvokeAsync("SI_OA_OA04_OUT", new object[] {
                        MT_OA_OA04}, this.SI_OA_OA04_OUTOperationCompleted, userState);
        }
        
        private void OnSI_OA_OA04_OUTOperationCompleted(object arg) {
            if ((this.SI_OA_OA04_OUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SI_OA_OA04_OUTCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA04 {
        
        private DT_OA_OA04HEADER hEADERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_OA_OA04HEADER HEADER {
            get {
                return this.hEADERField;
            }
            set {
                this.hEADERField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA04HEADER {
        
        private string bUKRSField;
        
        private string zFKDHField;
        
        private string zJYLXField;
        
        private string bANKAField;
        
        private string kOINHField;
        
        private string zBKNOField;
        
        private string zJYJEField;
        
        private string wAERSField;
        
        private string zZHTYField;
        
        private string bKTXTField;
        
        private string zPRCTField;
        
        private string eACBNKField;
        
        private string zCTNOField;
        
        private string cDTBRDField;
        
        private DT_OA_OA04HEADERITEM[] iTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZFKDH {
            get {
                return this.zFKDHField;
            }
            set {
                this.zFKDHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZJYLX {
            get {
                return this.zJYLXField;
            }
            set {
                this.zJYLXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BANKA {
            get {
                return this.bANKAField;
            }
            set {
                this.bANKAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KOINH {
            get {
                return this.kOINHField;
            }
            set {
                this.kOINHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBKNO {
            get {
                return this.zBKNOField;
            }
            set {
                this.zBKNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZJYJE {
            get {
                return this.zJYJEField;
            }
            set {
                this.zJYJEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZHTY {
            get {
                return this.zZHTYField;
            }
            set {
                this.zZHTYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BKTXT {
            get {
                return this.bKTXTField;
            }
            set {
                this.bKTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZPRCT {
            get {
                return this.zPRCTField;
            }
            set {
                this.zPRCTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EACBNK {
            get {
                return this.eACBNKField;
            }
            set {
                this.eACBNKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCTNO {
            get {
                return this.zCTNOField;
            }
            set {
                this.zCTNOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CDTBRD {
            get {
                return this.cDTBRDField;
            }
            set {
                this.cDTBRDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DT_OA_OA04HEADERITEM[] ITEM {
            get {
                return this.iTEMField;
            }
            set {
                this.iTEMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA04HEADERITEM {
        
        private string zNUMField;
        
        private string kOSTLField;
        
        private string hKONTField;
        
        private string zCBJEField;
        
        private string zZSKTField;
        
        private string zSHUEField;
        
        private string zBXJEField;
        
        private string zRMTXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZNUM {
            get {
                return this.zNUMField;
            }
            set {
                this.zNUMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HKONT {
            get {
                return this.hKONTField;
            }
            set {
                this.hKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZCBJE {
            get {
                return this.zCBJEField;
            }
            set {
                this.zCBJEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZSKT {
            get {
                return this.zZSKTField;
            }
            set {
                this.zZSKTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZSHUE {
            get {
                return this.zSHUEField;
            }
            set {
                this.zSHUEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZBXJE {
            get {
                return this.zBXJEField;
            }
            set {
                this.zBXJEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZRMTXT {
            get {
                return this.zRMTXTField;
            }
            set {
                this.zRMTXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SI_OA_OA04_OUTCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591