//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace OAService.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="OaWebServiceSoap", Namespace="http://jiuzhou.com/")]
    public partial class OaWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SAP_OA_JK_12OperationCompleted;
        
        private System.Threading.SendOrPostCallback SAP_OA_JK_06OperationCompleted;
        
        private System.Threading.SendOrPostCallback SAP_OA_JK_08OperationCompleted;
        
        private System.Threading.SendOrPostCallback SAP_OA_JK_13OperationCompleted;
        
        private System.Threading.SendOrPostCallback SAP_OA_JK_17OperationCompleted;
        
        private System.Threading.SendOrPostCallback SAP_OA_JK_15OperationCompleted;
        
        private System.Threading.SendOrPostCallback SAP_OA_JK_11OperationCompleted;
        
        private System.Threading.SendOrPostCallback SAP_OA_JK_20OperationCompleted;
        
        private System.Threading.SendOrPostCallback SAP_OA_JK_04OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public OaWebService() {
            this.Url = global::OAService.Properties.Settings.Default.OAService_WebReference_OaWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SAP_OA_JK_12CompletedEventHandler SAP_OA_JK_12Completed;
        
        /// <remarks/>
        public event SAP_OA_JK_06CompletedEventHandler SAP_OA_JK_06Completed;
        
        /// <remarks/>
        public event SAP_OA_JK_08CompletedEventHandler SAP_OA_JK_08Completed;
        
        /// <remarks/>
        public event SAP_OA_JK_13CompletedEventHandler SAP_OA_JK_13Completed;
        
        /// <remarks/>
        public event SAP_OA_JK_17CompletedEventHandler SAP_OA_JK_17Completed;
        
        /// <remarks/>
        public event SAP_OA_JK_15CompletedEventHandler SAP_OA_JK_15Completed;
        
        /// <remarks/>
        public event SAP_OA_JK_11CompletedEventHandler SAP_OA_JK_11Completed;
        
        /// <remarks/>
        public event SAP_OA_JK_20CompletedEventHandler SAP_OA_JK_20Completed;
        
        /// <remarks/>
        public event SAP_OA_JK_04CompletedEventHandler SAP_OA_JK_04Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jiuzhou.com/SAP_OA_JK_12", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute(Namespace="http://jiuzhou.com/")]
        public DT_OA_OA12_RespITEM[] SAP_OA_JK_12([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_12")] string uid) {
            object[] results = this.Invoke("SAP_OA_JK_12", new object[] {
                        uid});
            return ((DT_OA_OA12_RespITEM[])(results[0]));
        }
        
        /// <remarks/>
        public void SAP_OA_JK_12Async(string uid) {
            this.SAP_OA_JK_12Async(uid, null);
        }
        
        /// <remarks/>
        public void SAP_OA_JK_12Async(string uid, object userState) {
            if ((this.SAP_OA_JK_12OperationCompleted == null)) {
                this.SAP_OA_JK_12OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSAP_OA_JK_12OperationCompleted);
            }
            this.InvokeAsync("SAP_OA_JK_12", new object[] {
                        uid}, this.SAP_OA_JK_12OperationCompleted, userState);
        }
        
        private void OnSAP_OA_JK_12OperationCompleted(object arg) {
            if ((this.SAP_OA_JK_12Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SAP_OA_JK_12Completed(this, new SAP_OA_JK_12CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jiuzhou.com/SAP_OA_JK_06", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SAP_OA_JK_06([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_06")] [System.Xml.Serialization.XmlArrayItemAttribute("HEAD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] ZRFC_HR_OA_001_HEAD[] ZRFC_HR_OA_001_REQ) {
            this.Invoke("SAP_OA_JK_06", new object[] {
                        ZRFC_HR_OA_001_REQ});
        }
        
        /// <remarks/>
        public void SAP_OA_JK_06Async(ZRFC_HR_OA_001_HEAD[] ZRFC_HR_OA_001_REQ) {
            this.SAP_OA_JK_06Async(ZRFC_HR_OA_001_REQ, null);
        }
        
        /// <remarks/>
        public void SAP_OA_JK_06Async(ZRFC_HR_OA_001_HEAD[] ZRFC_HR_OA_001_REQ, object userState) {
            if ((this.SAP_OA_JK_06OperationCompleted == null)) {
                this.SAP_OA_JK_06OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSAP_OA_JK_06OperationCompleted);
            }
            this.InvokeAsync("SAP_OA_JK_06", new object[] {
                        ZRFC_HR_OA_001_REQ}, this.SAP_OA_JK_06OperationCompleted, userState);
        }
        
        private void OnSAP_OA_JK_06OperationCompleted(object arg) {
            if ((this.SAP_OA_JK_06Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SAP_OA_JK_06Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jiuzhou.com/SAP_OA_JK_08", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SAP_OA_JK_08([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_08")] [System.Xml.Serialization.XmlArrayItemAttribute("HEAD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] ZRFC_HR_OA_003_REQHEAD[] ZRFC_HR_OA_003_REQ) {
            this.Invoke("SAP_OA_JK_08", new object[] {
                        ZRFC_HR_OA_003_REQ});
        }
        
        /// <remarks/>
        public void SAP_OA_JK_08Async(ZRFC_HR_OA_003_REQHEAD[] ZRFC_HR_OA_003_REQ) {
            this.SAP_OA_JK_08Async(ZRFC_HR_OA_003_REQ, null);
        }
        
        /// <remarks/>
        public void SAP_OA_JK_08Async(ZRFC_HR_OA_003_REQHEAD[] ZRFC_HR_OA_003_REQ, object userState) {
            if ((this.SAP_OA_JK_08OperationCompleted == null)) {
                this.SAP_OA_JK_08OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSAP_OA_JK_08OperationCompleted);
            }
            this.InvokeAsync("SAP_OA_JK_08", new object[] {
                        ZRFC_HR_OA_003_REQ}, this.SAP_OA_JK_08OperationCompleted, userState);
        }
        
        private void OnSAP_OA_JK_08OperationCompleted(object arg) {
            if ((this.SAP_OA_JK_08Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SAP_OA_JK_08Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jiuzhou.com/SAP_OA_JK_13", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute(Namespace="http://jiuzhou.com/")]
        public DT_OA_OA13_RespITEM[] SAP_OA_JK_13([System.Xml.Serialization.XmlArrayAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_13")] [System.Xml.Serialization.XmlArrayItemAttribute("HEAD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] SAP_OA_JK13_HEAD[] SAP_OA_JK13_REQ) {
            object[] results = this.Invoke("SAP_OA_JK_13", new object[] {
                        SAP_OA_JK13_REQ});
            return ((DT_OA_OA13_RespITEM[])(results[0]));
        }
        
        /// <remarks/>
        public void SAP_OA_JK_13Async(SAP_OA_JK13_HEAD[] SAP_OA_JK13_REQ) {
            this.SAP_OA_JK_13Async(SAP_OA_JK13_REQ, null);
        }
        
        /// <remarks/>
        public void SAP_OA_JK_13Async(SAP_OA_JK13_HEAD[] SAP_OA_JK13_REQ, object userState) {
            if ((this.SAP_OA_JK_13OperationCompleted == null)) {
                this.SAP_OA_JK_13OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSAP_OA_JK_13OperationCompleted);
            }
            this.InvokeAsync("SAP_OA_JK_13", new object[] {
                        SAP_OA_JK13_REQ}, this.SAP_OA_JK_13OperationCompleted, userState);
        }
        
        private void OnSAP_OA_JK_13OperationCompleted(object arg) {
            if ((this.SAP_OA_JK_13Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SAP_OA_JK_13Completed(this, new SAP_OA_JK_13CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jiuzhou.com/SAP_OA_JK_17", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute(Namespace="http://jiuzhou.com/")]
        public DT_OA_OA17_RespITEM[] SAP_OA_JK_17([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_17")] SAP_OA_JK17_REQ SAP_OA_JK17_REQ) {
            object[] results = this.Invoke("SAP_OA_JK_17", new object[] {
                        SAP_OA_JK17_REQ});
            return ((DT_OA_OA17_RespITEM[])(results[0]));
        }
        
        /// <remarks/>
        public void SAP_OA_JK_17Async(SAP_OA_JK17_REQ SAP_OA_JK17_REQ) {
            this.SAP_OA_JK_17Async(SAP_OA_JK17_REQ, null);
        }
        
        /// <remarks/>
        public void SAP_OA_JK_17Async(SAP_OA_JK17_REQ SAP_OA_JK17_REQ, object userState) {
            if ((this.SAP_OA_JK_17OperationCompleted == null)) {
                this.SAP_OA_JK_17OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSAP_OA_JK_17OperationCompleted);
            }
            this.InvokeAsync("SAP_OA_JK_17", new object[] {
                        SAP_OA_JK17_REQ}, this.SAP_OA_JK_17OperationCompleted, userState);
        }
        
        private void OnSAP_OA_JK_17OperationCompleted(object arg) {
            if ((this.SAP_OA_JK_17Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SAP_OA_JK_17Completed(this, new SAP_OA_JK_17CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jiuzhou.com/SAP_OA_JK_15", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute(Namespace="http://jiuzhou.com/")]
        public DT_OA_OA15_RespITEM[] SAP_OA_JK_15([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_15")] SAP_OA_JK15_REQ SAP_OA_JK_15_REQ) {
            object[] results = this.Invoke("SAP_OA_JK_15", new object[] {
                        SAP_OA_JK_15_REQ});
            return ((DT_OA_OA15_RespITEM[])(results[0]));
        }
        
        /// <remarks/>
        public void SAP_OA_JK_15Async(SAP_OA_JK15_REQ SAP_OA_JK_15_REQ) {
            this.SAP_OA_JK_15Async(SAP_OA_JK_15_REQ, null);
        }
        
        /// <remarks/>
        public void SAP_OA_JK_15Async(SAP_OA_JK15_REQ SAP_OA_JK_15_REQ, object userState) {
            if ((this.SAP_OA_JK_15OperationCompleted == null)) {
                this.SAP_OA_JK_15OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSAP_OA_JK_15OperationCompleted);
            }
            this.InvokeAsync("SAP_OA_JK_15", new object[] {
                        SAP_OA_JK_15_REQ}, this.SAP_OA_JK_15OperationCompleted, userState);
        }
        
        private void OnSAP_OA_JK_15OperationCompleted(object arg) {
            if ((this.SAP_OA_JK_15Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SAP_OA_JK_15Completed(this, new SAP_OA_JK_15CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jiuzhou.com/SAP_OA_JK_11", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute(Namespace="http://jiuzhou.com/")]
        public DT_OA_OA11_RespITEM[] SAP_OA_JK_11([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_11")] SAP_OA_JK11_REQ SAP_OA_JK_11_REQ) {
            object[] results = this.Invoke("SAP_OA_JK_11", new object[] {
                        SAP_OA_JK_11_REQ});
            return ((DT_OA_OA11_RespITEM[])(results[0]));
        }
        
        /// <remarks/>
        public void SAP_OA_JK_11Async(SAP_OA_JK11_REQ SAP_OA_JK_11_REQ) {
            this.SAP_OA_JK_11Async(SAP_OA_JK_11_REQ, null);
        }
        
        /// <remarks/>
        public void SAP_OA_JK_11Async(SAP_OA_JK11_REQ SAP_OA_JK_11_REQ, object userState) {
            if ((this.SAP_OA_JK_11OperationCompleted == null)) {
                this.SAP_OA_JK_11OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSAP_OA_JK_11OperationCompleted);
            }
            this.InvokeAsync("SAP_OA_JK_11", new object[] {
                        SAP_OA_JK_11_REQ}, this.SAP_OA_JK_11OperationCompleted, userState);
        }
        
        private void OnSAP_OA_JK_11OperationCompleted(object arg) {
            if ((this.SAP_OA_JK_11Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SAP_OA_JK_11Completed(this, new SAP_OA_JK_11CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jiuzhou.com/SAP_OA_JK_20", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlArrayAttribute(Namespace="http://jiuzhou.com/")]
        public DT_OA_OA20_RespITEM[] SAP_OA_JK_20([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_20")] SAP_OA_JK20_REQ SAP_OA_JK_20_REQ) {
            object[] results = this.Invoke("SAP_OA_JK_20", new object[] {
                        SAP_OA_JK_20_REQ});
            return ((DT_OA_OA20_RespITEM[])(results[0]));
        }
        
        /// <remarks/>
        public void SAP_OA_JK_20Async(SAP_OA_JK20_REQ SAP_OA_JK_20_REQ) {
            this.SAP_OA_JK_20Async(SAP_OA_JK_20_REQ, null);
        }
        
        /// <remarks/>
        public void SAP_OA_JK_20Async(SAP_OA_JK20_REQ SAP_OA_JK_20_REQ, object userState) {
            if ((this.SAP_OA_JK_20OperationCompleted == null)) {
                this.SAP_OA_JK_20OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSAP_OA_JK_20OperationCompleted);
            }
            this.InvokeAsync("SAP_OA_JK_20", new object[] {
                        SAP_OA_JK_20_REQ}, this.SAP_OA_JK_20OperationCompleted, userState);
        }
        
        private void OnSAP_OA_JK_20OperationCompleted(object arg) {
            if ((this.SAP_OA_JK_20Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SAP_OA_JK_20Completed(this, new SAP_OA_JK_20CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://jiuzhou.com/SAP_OA_JK_04", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void SAP_OA_JK_04([System.Xml.Serialization.XmlElementAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_04")] SAP_OA_JK04_REQ SAP_OA_JK04_REQ) {
            this.Invoke("SAP_OA_JK_04", new object[] {
                        SAP_OA_JK04_REQ});
        }
        
        /// <remarks/>
        public void SAP_OA_JK_04Async(SAP_OA_JK04_REQ SAP_OA_JK04_REQ) {
            this.SAP_OA_JK_04Async(SAP_OA_JK04_REQ, null);
        }
        
        /// <remarks/>
        public void SAP_OA_JK_04Async(SAP_OA_JK04_REQ SAP_OA_JK04_REQ, object userState) {
            if ((this.SAP_OA_JK_04OperationCompleted == null)) {
                this.SAP_OA_JK_04OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSAP_OA_JK_04OperationCompleted);
            }
            this.InvokeAsync("SAP_OA_JK_04", new object[] {
                        SAP_OA_JK04_REQ}, this.SAP_OA_JK_04OperationCompleted, userState);
        }
        
        private void OnSAP_OA_JK_04OperationCompleted(object arg) {
            if ((this.SAP_OA_JK_04Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SAP_OA_JK_04Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA12_RespITEM {
        
        private string aWARTField;
        
        private string aTEXTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AWART {
            get {
                return this.aWARTField;
            }
            set {
                this.aWARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ATEXT {
            get {
                return this.aTEXTField;
            }
            set {
                this.aTEXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_04")]
    public partial class SAP_OA_JK04_HEAD_ITEM {
        
        private string zNUMField;
        
        private string kOSTLField;
        
        private string hKONTField;
        
        private string zCBJEField;
        
        private string zZSKTField;
        
        private string zSHUEField;
        
        private string zBXJEField;
        
        private string zRMTXTField;
        
        /// <remarks/>
        public string ZNUM {
            get {
                return this.zNUMField;
            }
            set {
                this.zNUMField = value;
            }
        }
        
        /// <remarks/>
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
        
        /// <remarks/>
        public string HKONT {
            get {
                return this.hKONTField;
            }
            set {
                this.hKONTField = value;
            }
        }
        
        /// <remarks/>
        public string ZCBJE {
            get {
                return this.zCBJEField;
            }
            set {
                this.zCBJEField = value;
            }
        }
        
        /// <remarks/>
        public string ZZSKT {
            get {
                return this.zZSKTField;
            }
            set {
                this.zZSKTField = value;
            }
        }
        
        /// <remarks/>
        public string ZSHUE {
            get {
                return this.zSHUEField;
            }
            set {
                this.zSHUEField = value;
            }
        }
        
        /// <remarks/>
        public string ZBXJE {
            get {
                return this.zBXJEField;
            }
            set {
                this.zBXJEField = value;
            }
        }
        
        /// <remarks/>
        public string ZRMTXT {
            get {
                return this.zRMTXTField;
            }
            set {
                this.zRMTXTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_04")]
    public partial class SAP_OA_JK04_HEAD {
        
        private string bUKRSField;
        
        private string zFKDHField;
        
        private string zJYLXField;
        
        private string bANKAField;
        
        private string kOINHField;
        
        private string zBKNOField;
        
        private string zJYJEField;
        
        private string wAERSField;
        
        private string zZHTYField;
        
        private string bKTXTField;
        
        private SAP_OA_JK04_HEAD_ITEM[] iTEMSField;
        
        /// <remarks/>
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        public string ZFKDH {
            get {
                return this.zFKDHField;
            }
            set {
                this.zFKDHField = value;
            }
        }
        
        /// <remarks/>
        public string ZJYLX {
            get {
                return this.zJYLXField;
            }
            set {
                this.zJYLXField = value;
            }
        }
        
        /// <remarks/>
        public string BANKA {
            get {
                return this.bANKAField;
            }
            set {
                this.bANKAField = value;
            }
        }
        
        /// <remarks/>
        public string KOINH {
            get {
                return this.kOINHField;
            }
            set {
                this.kOINHField = value;
            }
        }
        
        /// <remarks/>
        public string ZBKNO {
            get {
                return this.zBKNOField;
            }
            set {
                this.zBKNOField = value;
            }
        }
        
        /// <remarks/>
        public string ZJYJE {
            get {
                return this.zJYJEField;
            }
            set {
                this.zJYJEField = value;
            }
        }
        
        /// <remarks/>
        public string WAERS {
            get {
                return this.wAERSField;
            }
            set {
                this.wAERSField = value;
            }
        }
        
        /// <remarks/>
        public string ZZHTY {
            get {
                return this.zZHTYField;
            }
            set {
                this.zZHTYField = value;
            }
        }
        
        /// <remarks/>
        public string BKTXT {
            get {
                return this.bKTXTField;
            }
            set {
                this.bKTXTField = value;
            }
        }
        
        /// <remarks/>
        public SAP_OA_JK04_HEAD_ITEM[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_04")]
    public partial class SAP_OA_JK04_REQ {
        
        private SAP_OA_JK04_HEAD hEADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SAP_OA_JK04_HEAD HEAD {
            get {
                return this.hEADField;
            }
            set {
                this.hEADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA20_RespITEM {
        
        private string mSGIDField;
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_20")]
    public partial class SAP_OA_JK20_HEAD {
        
        private string i_PERNRField;
        
        private string i_BEGDAField;
        
        private string i_MASSGField;
        
        /// <remarks/>
        public string I_PERNR {
            get {
                return this.i_PERNRField;
            }
            set {
                this.i_PERNRField = value;
            }
        }
        
        /// <remarks/>
        public string I_BEGDA {
            get {
                return this.i_BEGDAField;
            }
            set {
                this.i_BEGDAField = value;
            }
        }
        
        /// <remarks/>
        public string I_MASSG {
            get {
                return this.i_MASSGField;
            }
            set {
                this.i_MASSGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_20")]
    public partial class SAP_OA_JK20_REQ {
        
        private SAP_OA_JK20_HEAD hEADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SAP_OA_JK20_HEAD HEAD {
            get {
                return this.hEADField;
            }
            set {
                this.hEADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA11_RespITEM {
        
        private string mSGIDField;
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private string pERNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_11")]
    public partial class SAP_OA_JK11_HEAD {
        
        private string pERNRField;
        
        private string lDATEField;
        
        private string lTIMEField;
        
        private string sATZAField;
        
        private string aBWGRField;
        
        /// <remarks/>
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
        
        /// <remarks/>
        public string LDATE {
            get {
                return this.lDATEField;
            }
            set {
                this.lDATEField = value;
            }
        }
        
        /// <remarks/>
        public string LTIME {
            get {
                return this.lTIMEField;
            }
            set {
                this.lTIMEField = value;
            }
        }
        
        /// <remarks/>
        public string SATZA {
            get {
                return this.sATZAField;
            }
            set {
                this.sATZAField = value;
            }
        }
        
        /// <remarks/>
        public string ABWGR {
            get {
                return this.aBWGRField;
            }
            set {
                this.aBWGRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_11")]
    public partial class SAP_OA_JK11_REQ {
        
        private SAP_OA_JK11_HEAD hEADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SAP_OA_JK11_HEAD HEAD {
            get {
                return this.hEADField;
            }
            set {
                this.hEADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA15_RespITEM {
        
        private string mSGIDField;
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private string pERNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_15")]
    public partial class SAP_OA_JK15_HEAD {
        
        private string i_PERNRField;
        
        private string i_BEGDAField;
        
        private string i_ENDDAField;
        
        private string i_AWARTField;
        
        /// <remarks/>
        public string I_PERNR {
            get {
                return this.i_PERNRField;
            }
            set {
                this.i_PERNRField = value;
            }
        }
        
        /// <remarks/>
        public string I_BEGDA {
            get {
                return this.i_BEGDAField;
            }
            set {
                this.i_BEGDAField = value;
            }
        }
        
        /// <remarks/>
        public string I_ENDDA {
            get {
                return this.i_ENDDAField;
            }
            set {
                this.i_ENDDAField = value;
            }
        }
        
        /// <remarks/>
        public string I_AWART {
            get {
                return this.i_AWARTField;
            }
            set {
                this.i_AWARTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_15")]
    public partial class SAP_OA_JK15_REQ {
        
        private SAP_OA_JK15_HEAD hEADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SAP_OA_JK15_HEAD HEAD {
            get {
                return this.hEADField;
            }
            set {
                this.hEADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA17_RespITEM {
        
        private string mSGIDField;
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private string pERNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_17")]
    public partial class SAP_OA_JK17_HEAD {
        
        private string i_PERNRField;
        
        private string i_BEGDAField;
        
        private string i_ENDDAField;
        
        private string i_BEGUZField;
        
        private string i_ENDUZField;
        
        private string i_STDAZField;
        
        private string i_VERSLField;
        
        /// <remarks/>
        public string I_PERNR {
            get {
                return this.i_PERNRField;
            }
            set {
                this.i_PERNRField = value;
            }
        }
        
        /// <remarks/>
        public string I_BEGDA {
            get {
                return this.i_BEGDAField;
            }
            set {
                this.i_BEGDAField = value;
            }
        }
        
        /// <remarks/>
        public string I_ENDDA {
            get {
                return this.i_ENDDAField;
            }
            set {
                this.i_ENDDAField = value;
            }
        }
        
        /// <remarks/>
        public string I_BEGUZ {
            get {
                return this.i_BEGUZField;
            }
            set {
                this.i_BEGUZField = value;
            }
        }
        
        /// <remarks/>
        public string I_ENDUZ {
            get {
                return this.i_ENDUZField;
            }
            set {
                this.i_ENDUZField = value;
            }
        }
        
        /// <remarks/>
        public string I_STDAZ {
            get {
                return this.i_STDAZField;
            }
            set {
                this.i_STDAZField = value;
            }
        }
        
        /// <remarks/>
        public string I_VERSL {
            get {
                return this.i_VERSLField;
            }
            set {
                this.i_VERSLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_17")]
    public partial class SAP_OA_JK17_REQ {
        
        private SAP_OA_JK17_HEAD hEADField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SAP_OA_JK17_HEAD HEAD {
            get {
                return this.hEADField;
            }
            set {
                this.hEADField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/OA")]
    public partial class DT_OA_OA13_RespITEM {
        
        private string mSGIDField;
        
        private string tYPEField;
        
        private string mESSAGEField;
        
        private string i_PERNRField;
        
        private string i_BEGDAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MSGID {
            get {
                return this.mSGIDField;
            }
            set {
                this.mSGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_PERNR {
            get {
                return this.i_PERNRField;
            }
            set {
                this.i_PERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string I_BEGDA {
            get {
                return this.i_BEGDAField;
            }
            set {
                this.i_BEGDAField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_13")]
    public partial class SAP_OA_JK13_HEAD {
        
        private string i_PERNRField;
        
        private string i_BEGDAField;
        
        private string l_HALFField;
        
        private string l_BEGUZField;
        
        private string l_ENDUZField;
        
        private string i_AWARTField;
        
        /// <remarks/>
        public string I_PERNR {
            get {
                return this.i_PERNRField;
            }
            set {
                this.i_PERNRField = value;
            }
        }
        
        /// <remarks/>
        public string I_BEGDA {
            get {
                return this.i_BEGDAField;
            }
            set {
                this.i_BEGDAField = value;
            }
        }
        
        /// <remarks/>
        public string L_HALF {
            get {
                return this.l_HALFField;
            }
            set {
                this.l_HALFField = value;
            }
        }
        
        /// <remarks/>
        public string L_BEGUZ {
            get {
                return this.l_BEGUZField;
            }
            set {
                this.l_BEGUZField = value;
            }
        }
        
        /// <remarks/>
        public string L_ENDUZ {
            get {
                return this.l_ENDUZField;
            }
            set {
                this.l_ENDUZField = value;
            }
        }
        
        /// <remarks/>
        public string I_AWART {
            get {
                return this.i_AWARTField;
            }
            set {
                this.i_AWARTField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://jiuzhou.com/SAP_OA_JK_06")]
    public partial class ZRFC_HR_OA_001_HEAD {
        
        private string bJIDField;
        
        private string sTEXTField;
        
        private string pUPField;
        
        private string nUMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BJID {
            get {
                return this.bJIDField;
            }
            set {
                this.bJIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STEXT {
            get {
                return this.sTEXTField;
            }
            set {
                this.sTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PUP {
            get {
                return this.pUPField;
            }
            set {
                this.pUPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NUM {
            get {
                return this.nUMField;
            }
            set {
                this.nUMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://jiuzhou.com/SAP_OA_JK_08")]
    public partial class ZRFC_HR_OA_003_REQHEAD {
        
        private string nACHNField;
        
        private string pERNRField;
        
        private string pERSGField;
        
        private string pTEXTField;
        
        private string pERSKField;
        
        private string pTEXT1Field;
        
        private string gESCHField;
        
        private string uSRID_LONGField;
        
        private string uSRIDField;
        
        private string oBJID_DEPField;
        
        private string oRGTXField;
        
        private string oBJID_COMField;
        
        private string sTEXT_GSPField;
        
        private string oBJID_SField;
        
        private string oBJTXT_SField;
        
        private string gBDATField;
        
        private string bEGDAField;
        
        private string sYSTEMField;
        
        private string lOGIDField;
        
        private string sTELLField;
        
        private string sTLTXField;
        
        private string sTAT2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NACHN {
            get {
                return this.nACHNField;
            }
            set {
                this.nACHNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERNR {
            get {
                return this.pERNRField;
            }
            set {
                this.pERNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERSG {
            get {
                return this.pERSGField;
            }
            set {
                this.pERSGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PTEXT {
            get {
                return this.pTEXTField;
            }
            set {
                this.pTEXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PERSK {
            get {
                return this.pERSKField;
            }
            set {
                this.pERSKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PTEXT1 {
            get {
                return this.pTEXT1Field;
            }
            set {
                this.pTEXT1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GESCH {
            get {
                return this.gESCHField;
            }
            set {
                this.gESCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USRID_LONG {
            get {
                return this.uSRID_LONGField;
            }
            set {
                this.uSRID_LONGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string USRID {
            get {
                return this.uSRIDField;
            }
            set {
                this.uSRIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBJID_DEP {
            get {
                return this.oBJID_DEPField;
            }
            set {
                this.oBJID_DEPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORGTX {
            get {
                return this.oRGTXField;
            }
            set {
                this.oRGTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBJID_COM {
            get {
                return this.oBJID_COMField;
            }
            set {
                this.oBJID_COMField = value;
            }
        }
        
        /// <remarks/>
        public string STEXT_GSP {
            get {
                return this.sTEXT_GSPField;
            }
            set {
                this.sTEXT_GSPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBJID_S {
            get {
                return this.oBJID_SField;
            }
            set {
                this.oBJID_SField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OBJTXT_S {
            get {
                return this.oBJTXT_SField;
            }
            set {
                this.oBJTXT_SField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GBDAT {
            get {
                return this.gBDATField;
            }
            set {
                this.gBDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BEGDA {
            get {
                return this.bEGDAField;
            }
            set {
                this.bEGDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LOGID {
            get {
                return this.lOGIDField;
            }
            set {
                this.lOGIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STELL {
            get {
                return this.sTELLField;
            }
            set {
                this.sTELLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STLTX {
            get {
                return this.sTLTXField;
            }
            set {
                this.sTLTXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STAT2 {
            get {
                return this.sTAT2Field;
            }
            set {
                this.sTAT2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SAP_OA_JK_12CompletedEventHandler(object sender, SAP_OA_JK_12CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SAP_OA_JK_12CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SAP_OA_JK_12CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_OA_OA12_RespITEM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_OA_OA12_RespITEM[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SAP_OA_JK_06CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SAP_OA_JK_08CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SAP_OA_JK_13CompletedEventHandler(object sender, SAP_OA_JK_13CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SAP_OA_JK_13CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SAP_OA_JK_13CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_OA_OA13_RespITEM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_OA_OA13_RespITEM[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SAP_OA_JK_17CompletedEventHandler(object sender, SAP_OA_JK_17CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SAP_OA_JK_17CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SAP_OA_JK_17CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_OA_OA17_RespITEM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_OA_OA17_RespITEM[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SAP_OA_JK_15CompletedEventHandler(object sender, SAP_OA_JK_15CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SAP_OA_JK_15CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SAP_OA_JK_15CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_OA_OA15_RespITEM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_OA_OA15_RespITEM[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SAP_OA_JK_11CompletedEventHandler(object sender, SAP_OA_JK_11CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SAP_OA_JK_11CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SAP_OA_JK_11CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_OA_OA11_RespITEM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_OA_OA11_RespITEM[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SAP_OA_JK_20CompletedEventHandler(object sender, SAP_OA_JK_20CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SAP_OA_JK_20CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SAP_OA_JK_20CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DT_OA_OA20_RespITEM[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DT_OA_OA20_RespITEM[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SAP_OA_JK_04CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591