//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JZWebService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://linux-tz11:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "S_OA_DEV&receiverParty=&receiverService=&interface=SI_OA_OA13_OUT&interfaceNames" +
            "pace=http%3A%2F%2Fjiuzhou.com%2FOA")]
        public string JZWebService_SapOa13Webservice_SI_OA_OA13_OUTService {
            get {
                return ((string)(this["JZWebService_SapOa13Webservice_SI_OA_OA13_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://linux-tz11:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "S_OA_DEV&receiverParty=&receiverService=&interface=SI_OA_OA12_OUT&interfaceNames" +
            "pace=http%3A%2F%2Fjiuzhou.com%2FOA")]
        public string JZWebService_SapOa12Webservice_SI_OA_OA12_OUTService {
            get {
                return ((string)(this["JZWebService_SapOa12Webservice_SI_OA_OA12_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://linux-tz11:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "S_OA_DEV&receiverParty=&receiverService=&interface=SI_OA_OA17_OUT&interfaceNames" +
            "pace=http%3A%2F%2Fjiuzhou.com%2FOA")]
        public string JZWebService_SapOa17Webservice_SI_OA_OA17_OUTService {
            get {
                return ((string)(this["JZWebService_SapOa17Webservice_SI_OA_OA17_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://linux-tz11:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "S_OA_DEV&receiverParty=&receiverService=&interface=SI_OA_OA15_OUT&interfaceNames" +
            "pace=http%3A%2F%2Fjiuzhou.com%2FOA")]
        public string JZWebService_SapOa15Webservice_SI_OA_OA15_OUTService {
            get {
                return ((string)(this["JZWebService_SapOa15Webservice_SI_OA_OA15_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://linux-tz11:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "S_OA_DEV&receiverParty=&receiverService=&interface=SI_OA_OA11_OUT&interfaceNames" +
            "pace=http%3A%2F%2Fjiuzhou.com%2FOA")]
        public string JZWebService_SapOa11Webservice_SI_OA_OA11_OUTService {
            get {
                return ((string)(this["JZWebService_SapOa11Webservice_SI_OA_OA11_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://linux-tz11:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "S_OA_DEV&receiverParty=&receiverService=&interface=SI_OA_OA14_OUT&interfaceNames" +
            "pace=http%3A%2F%2Fjiuzhou.com%2FOA")]
        public string JZWebService_SapOa14Webservice_SI_OA_OA14_OUTService {
            get {
                return ((string)(this["JZWebService_SapOa14Webservice_SI_OA_OA14_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://linux-tz11:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "S_OA_DEV&receiverParty=&receiverService=&interface=SI_OA_OA20_OUT&interfaceNames" +
            "pace=http%3A%2F%2Fjiuzhou.com%2FOA")]
        public string JZWebService_SapOa20Webservice_SI_OA_OA20_OUTService {
            get {
                return ((string)(this["JZWebService_SapOa20Webservice_SI_OA_OA20_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://linux-tz11:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "S_OA_DEV&receiverParty=&receiverService=&interface=SI_OA_OA04_OUT&interfaceNames" +
            "pace=http%3A%2F%2Fjiuzhou.com%2FOA")]
        public string JZWebService_SapOa04Webservice_SI_OA_OA04_OUTService {
            get {
                return ((string)(this["JZWebService_SapOa04Webservice_SI_OA_OA04_OUTService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://linux-tz11:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=B" +
            "S_OA_DEV&receiverParty=&receiverService=&interface=SI_OA_OA10_OUT&interfaceNames" +
            "pace=http%3A%2F%2Fjiuzhou.com%2FOA")]
        public string JZWebService_SapOa10WebService_SI_OA_OA10_OUTService {
            get {
                return ((string)(this["JZWebService_SapOa10WebService_SI_OA_OA10_OUTService"]));
            }
        }
    }
}
